In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [7]:
import numpy as np
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(arr.flatten())
print(arr.flatten('F'))

[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(np.array_equal(arr1,arr2))

True


In [18]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(x).argmax())
n=np.bincount(y)
for i in range(len(n)):
    if n[i]==max(n):
        print(i,end=" ")


1
1 3 

In [19]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(np.sum(gfg))
print(np.sum(gfg,axis=1))
print(np.sum(gfg,axis=0))


45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [22]:
import numpy as np
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
sum_diagonal = np.trace(n_array)
eigen_values, eigen_vectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant_matrix = np.linalg.det(n_array)
sum_diagonal, eigen_values, eigen_vectors, inverse_matrix, determinant_matrix


(176,
 array([98.16835147, 28.097044  , 49.73460452]),
 array([[ 0.4574917 ,  0.34637121, -0.15017693],
        [ 0.28447814, -0.72784061, -0.4852124 ],
        [ 0.84248058,  0.59184038,  0.8614034 ]]),
 array([[ 0.02404141, -0.00911212, -0.00444671],
        [-0.01667882,  0.02966905,  0.0024785 ],
        [ 0.00631287, -0.01603732,  0.01217379]]),
 137180.0000000001)

In [27]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
result_i = np.dot(p1, q1)
covariance_i = np.cov(p1.flatten(), q1.flatten())
print(result_i)
print(covariance_i) 

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
result_ii = np.dot(p2, q2)
covariance_ii = np.cov(p2.flatten(), q2.flatten()) 
result_ii, covariance_ii


[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]


(array([[16, 19,  5],
        [26, 31,  8],
        [46, 55, 14]]),
 array([[2.16666667, 0.23333333],
        [0.23333333, 5.36666667]]))

In [2]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:\n",np.inner(x,y))
print("Outer product:\n",np.outer(x,y))
print("Cartesian Product of matrices x and y:\n",np.cross(x,y))


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product of matrices x and y:
 [[-20   4   7]
 [-84  36  20]]


In [3]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
# i. Element-wise absolute value
abs_array = np.abs(array)
print("Absolute Value:\n", abs_array)


Absolute Value:
 [[1 2 3]
 [4 5 6]]


In [4]:
# ii. Percentiles of the flattened array, for each column, for each row
flattened = array.flatten()
percentiles_flattened = np.percentile(flattened, [25, 50, 75])

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("\nPercentiles of Flattened Array:", percentiles_flattened)
print("Percentiles for each Column:\n", percentiles_columns)
print("Percentiles for each Row:\n", percentiles_rows)


Percentiles of Flattened Array: [-3.5 -0.5  2.5]
Percentiles for each Column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each Row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [5]:
# iii. Mean, Median, and Standard Deviation of flattened array, of each column, and each row
mean_flattened = np.mean(flattened)
median_flattened = np.median(flattened)
std_flattened = np.std(flattened)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("\nMean, Median, Standard Deviation of Flattened Array:")
print("Mean:", mean_flattened, "Median:", median_flattened, "Std Dev:", std_flattened)

print("\nMean, Median, Standard Deviation for each Column:")
print("Mean:", mean_columns, "Median:", median_columns, "Std Dev:", std_columns)

print("\nMean, Median, Standard Deviation for each Row:")
print("Mean:", mean_rows, "Median:", median_rows, "Std Dev:", std_rows)


Mean, Median, Standard Deviation of Flattened Array:
Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224

Mean, Median, Standard Deviation for each Column:
Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std Dev: [2.5 3.5 4.5]

Mean, Median, Standard Deviation for each Row:
Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std Dev: [2.05480467 4.78423336]


In [6]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

# iii. 4 smallest elements
smallest_elements = np.sort(array)[:4]
print("4 smallest elements:", smallest_elements)

# iv. 5 largest elements
largest_elements = np.sort(array)[-5:]
print("5 largest elements:", largest_elements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [7]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements = array[array == np.floor(array)]
print("Integer elements only:", integer_elements)

# ii. Float elements only (excluding integers)
float_elements = array[array != np.floor(array)]
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]
